[package]
name = "codemp-nvim"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
codemp = { git = "ssh://git@github.com/codewithotherpeopleandchangenamelater/codemp.git", rev = "6fe07d560614dfeda289a3b86b8bc55d3065e17d", features = ["static"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.3.1", features = ["v4"] }
serde = "1"
serde_json = "1"
nvim-oxi = { version = "0.3.0", features = ["neovim-0-9", "mlua", "libuv"] }
lazy_static = "1.4.0"
